TOKEN = '5934219564:AAH8F42YYISlmMOM7YeMDFBRcg4F1tmiSZw'


DATABASE_USER = 'root'
DATABASE_PASSWORD = 'password'
DATABASE_HOST = 'localhost'
DATABASE_NAME = 'car_db'

# Ссылка на базу данных
MYSQL_URL = f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}'